/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package module;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.JOptionPane;
import javax.swing.UIManager;
import net.proteanit.sql.DbUtils;

/**
 *
 * @author JayJomJohn
 */
public class Mypage extends javax.swing.JFrame {

    Connection conn;
    ResultSet rs;
    PreparedStatement pst;
    
    public Mypage() {
        super("Home");
        initComponents();
        conn=JavaConnector.ConnectDb();
        Calendar();
        showCustomer();
        showBalance();
        Account();
    }

public final void Calendar(){
    Calendar cal = new GregorianCalendar();
    int month = cal.get(Calendar.MONTH);
    int year = cal.get(Calendar.YEAR);
    int day = cal.get(Calendar.DAY_OF_MONTH);
    txtdate.setText(+day+"-"+(month+1)+"-"+year);
}   

public void showCustomer(){
    try {
        String query = "SELECT account_no,name,date_of_birth,account_type,gender,mobile FROM accounts";
        pst=conn.prepareStatement(query);
        rs=pst.executeQuery();
        jTable1.setModel(DbUtils.resultSetToTableModel(rs));
        
    } catch (Exception e) {
    }
}

public void showBalance(){
    try {
        String query = "SELECT name,account,MICR_no,balances FROM balance";
        pst=conn.prepareStatement(query);
        rs=pst.executeQuery();
        jTable2.setModel(DbUtils.resultSetToTableModel(rs));
        
    } catch (Exception e) {
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        F1 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        F2 = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        F3 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        F4 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        F5 = new javax.swing.JTextField();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        F7 = new javax.swing.JTextField();
        F6 = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        F8 = new javax.swing.JTextField();
        F9 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        F10 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel26 = new javax.swing.JLabel();
        USER = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        jLabel27 = new javax.swing.JLabel();
        NAME = new javax.swing.JTextField();
        jLabel28 = new javax.swing.JLabel();
        ACCOUNTNO = new javax.swing.JTextField();
        jLabel29 = new javax.swing.JLabel();
        BALANCE = new javax.swing.JTextField();
        jLabel30 = new javax.swing.JLabel();
        TOTAL = new javax.swing.JTextField();
        DEPOSITAMOUNT = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        txtUser = new javax.swing.JTextField();
        txtName = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        txtAccountNo = new javax.swing.JTextField();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        txtAvailableBalance = new javax.swing.JTextField();
        jLabel35 = new javax.swing.JLabel();
        jTextfield24 = new javax.swing.JTextField();
        txtTranferAmount = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel36 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        txtTotaltransfer = new javax.swing.JTextField();
        jTextfield25 = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel37 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel38 = new javax.swing.JLabel();
        txtName1 = new javax.swing.JTextField();
        jLabel39 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel40 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jLabel41 = new javax.swing.JLabel();
        jTextField4 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jTextField5 = new javax.swing.JTextField();
        jButton11 = new javax.swing.JButton();
        jButton12 = new javax.swing.JButton();
        jButton13 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel8 = new javax.swing.JPanel();
        jLabel43 = new javax.swing.JLabel();
        jTextField6 = new javax.swing.JTextField();
        jTextField7 = new javax.swing.JTextField();
        jLabel44 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel45 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel46 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jLabel47 = new javax.swing.JLabel();
        jTextField11 = new javax.swing.JTextField();
        jLabel48 = new javax.swing.JLabel();
        jTextField12 = new javax.swing.JTextField();
        jLabel49 = new javax.swing.JLabel();
        jTextField13 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton14 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jTextField14 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField15 = new javax.swing.JTextField();
        jButton15 = new javax.swing.JButton();
        jButton16 = new javax.swing.JButton();
        jPanel10 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtuser = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        txtdate = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(899, 542));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTabbedPane1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jTabbedPane1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jTabbedPane1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel16.setText("NAME");
        jPanel2.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 130, 30));

        F1.setEditable(false);
        F1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 20, 170, 30));

        jLabel17.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel17.setText("DATE OF BIRTH");
        jPanel2.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 60, 130, 30));

        F2.setEditable(false);
        F2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F2, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 60, 170, 30));

        jLabel18.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel18.setText("NATIONALITY");
        jPanel2.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 100, 130, 30));

        F3.setEditable(false);
        F3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F3, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 100, 170, 30));

        jLabel19.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel19.setText("GENDER");
        jPanel2.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 130, 30));

        F4.setEditable(false);
        F4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F4, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 140, 170, 30));

        jLabel20.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel20.setText("ADDRESS");
        jPanel2.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 130, 30));

        F5.setEditable(false);
        F5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F5, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 170, 30));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel21.setText("ACCOUNT NO.");
        jPanel2.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 20, 130, 30));

        jLabel22.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel22.setText("ACCOUNT TYPE");
        jPanel2.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 60, 130, 30));

        F7.setEditable(false);
        F7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F7, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 60, 170, 30));

        F6.setEditable(false);
        F6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 20, 170, 30));

        jLabel23.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel23.setText("CASTE");
        jPanel2.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 100, 130, 30));

        F8.setEditable(false);
        F8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F8, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 100, 170, 30));

        F9.setEditable(false);
        F9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F9, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 140, 170, 30));

        jLabel24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel24.setText("MOBILE");
        jPanel2.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 140, 130, 30));

        jLabel25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel25.setText("SECURITY QUESTION");
        jPanel2.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 180, 170, 30));

        F10.setEditable(false);
        F10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        F10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(F10, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 180, 310, 30));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton1.setText("SAVE");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 180, 40));

        jButton3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton3.setText("EDIT");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 260, 180, 40));

        jTabbedPane1.addTab("PROFILE", jPanel2);

        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel26.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel26.setText("USER");
        jPanel3.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 50, 130, 30));

        USER.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        USER.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(USER, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 50, 170, 30));

        jButton4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton4.setText("DEPOSIT");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 330, 130, 30));

        jLabel27.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel27.setText("NAME");
        jPanel3.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 90, 130, 30));

        NAME.setEditable(false);
        NAME.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        NAME.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(NAME, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 90, 170, 30));

        jLabel28.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel28.setText("ACCOUNT NO.");
        jPanel3.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 130, 130, 30));

        ACCOUNTNO.setEditable(false);
        ACCOUNTNO.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ACCOUNTNO.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(ACCOUNTNO, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 170, 30));

        jLabel29.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel29.setText("AVAILABLE BALANCE:");
        jPanel3.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 180, 30));

        BALANCE.setEditable(false);
        BALANCE.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        BALANCE.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(BALANCE, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 170, 170, 30));

        jLabel30.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel30.setText("DEPOSIT AMOUNT:");
        jPanel3.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 160, 30));

        TOTAL.setEditable(false);
        TOTAL.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        TOTAL.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(TOTAL, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 100, 30));

        DEPOSITAMOUNT.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        DEPOSITAMOUNT.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel3.add(DEPOSITAMOUNT, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 260, 110, 30));

        jButton5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton5.setText("SEARCH");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 50, 130, 30));

        jButton6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton6.setText("TOTAL");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 130, 30));

        jTabbedPane1.addTab("DEPOSIT", jPanel3);

        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel31.setText("USER");
        jPanel4.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 170, 30));

        txtUser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtUser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtUser, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, 170, 30));

        txtName.setEditable(false);
        txtName.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 60, 170, 30));

        jLabel32.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel32.setText("NAME");
        jPanel4.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 60, 170, 30));

        txtAccountNo.setEditable(false);
        txtAccountNo.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAccountNo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtAccountNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 100, 170, 30));

        jLabel33.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel33.setText("ACCOUNT NO.");
        jPanel4.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 100, 170, 30));

        jLabel34.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel34.setText("AVAILABLE BALANCE:");
        jPanel4.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(159, 140, -1, 30));

        txtAvailableBalance.setEditable(false);
        txtAvailableBalance.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtAvailableBalance.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtAvailableBalance, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 140, 170, 30));

        jLabel35.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel35.setText("CREDIT ACCOUNT");
        jPanel4.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 220, -1, 30));

        jTextfield24.setEditable(false);
        jTextfield24.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextfield24.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jTextfield24, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 260, 120, 30));

        txtTranferAmount.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTranferAmount.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtTranferAmount, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 180, 170, 30));

        jButton7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton7.setText("TOTAL");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton7, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 180, 120, 30));

        jButton8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton8.setText("TRANSFER");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton8, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 260, 120, 30));

        jLabel36.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel36.setText("TRANSFER AMOUNT");
        jPanel4.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 180, -1, 30));

        jComboBox1.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
                jComboBox1PopupMenuWillBecomeInvisible(evt);
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
            }
        });
        jPanel4.add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 220, 170, 30));

        txtTotaltransfer.setEditable(false);
        txtTotaltransfer.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtTotaltransfer.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(txtTotaltransfer, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, 120, 30));

        jTextfield25.setEditable(false);
        jTextfield25.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextfield25.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel4.add(jTextfield25, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 220, 120, 30));

        jButton9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton9.setText("SEARCH");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton9, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 20, 120, 30));

        jButton10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton10.setText("SHOW");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });
        jPanel4.add(jButton10, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 120, 30));

        jTabbedPane1.addTab("TRANSFER", jPanel4);

        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel37.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel37.setText("USER");
        jPanel5.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 170, 30));

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 210, 30));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel38.setText("NAME");
        jPanel5.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 30));

        txtName1.setEditable(false);
        txtName1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtName1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(txtName1, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 210, 30));

        jLabel39.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel39.setText("ACCOUNT NO.");
        jPanel5.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, 30));

        jTextField2.setEditable(false);
        jTextField2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 210, 30));

        jLabel40.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel40.setText("AVAILABLE BALANCE");
        jPanel5.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 30));

        jTextField3.setEditable(false);
        jTextField3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField3, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 210, 30));

        jLabel41.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel41.setText("AMOUNT");
        jPanel5.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 180, 170, 30));

        jTextField4.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField4, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 210, 30));

        jLabel42.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel42.setText("TOTAL");
        jPanel5.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, 30));

        jTextField5.setEditable(false);
        jTextField5.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel5.add(jTextField5, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 210, 30));

        jButton11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton11.setText("WITHDRAW");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, 30));

        jButton12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton12.setText("SEARCH");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton12, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 130, 30));

        jButton13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton13.setText("SHOW");
        jButton13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton13ActionPerformed(evt);
            }
        });
        jPanel5.add(jButton13, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 220, 130, 30));

        jTabbedPane1.addTab("WITHDRAW", jPanel5);

        jTable1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setColumnSelectionAllowed(true);
        jTable1.setGridColor(new java.awt.Color(255, 255, 255));
        jTable1.setRowHeight(18);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        jTable1.getColumnModel().getSelectionModel().setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("CUSTOMER LIST", jPanel6);

        jTable2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable2.setGridColor(new java.awt.Color(255, 255, 255));
        jTable2.setRowHeight(18);
        jTable2.getTableHeader().setReorderingAllowed(false);
        jScrollPane2.setViewportView(jTable2);
        if (jTable2.getColumnModel().getColumnCount() > 0) {
            jTable2.getColumnModel().getColumn(0).setResizable(false);
            jTable2.getColumnModel().getColumn(1).setResizable(false);
            jTable2.getColumnModel().getColumn(2).setResizable(false);
            jTable2.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 853, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("TRANSACTION", jPanel7);

        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel43.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel43.setText("USER");
        jPanel8.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 170, 30));

        jTextField6.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 20, 210, 30));

        jTextField7.setEditable(false);
        jTextField7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 60, 210, 30));

        jLabel44.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel44.setText("NAME");
        jPanel8.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 60, 170, 30));

        jTextField8.setEditable(false);
        jTextField8.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField8.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField8, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 100, 210, 30));

        jLabel45.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel45.setText("ACCOUNT NO");
        jPanel8.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 100, 170, 30));

        jTextField9.setEditable(false);
        jTextField9.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField9.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField9, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 140, 210, 30));

        jLabel46.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel46.setText("MICR NO.");
        jPanel8.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 140, 170, 30));

        jTextField10.setEditable(false);
        jTextField10.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField10.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 180, 210, 30));

        jLabel47.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel47.setText("RATE OF INTEREST (%)");
        jPanel8.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 180, 180, 30));

        jTextField11.setEditable(false);
        jTextField11.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField11.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField11, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 220, 210, 30));

        jLabel48.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel48.setText("AVAILABLE BALANCE");
        jPanel8.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 220, 170, 30));

        jTextField12.setEditable(false);
        jTextField12.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField12.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField12, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 260, 210, 30));

        jLabel49.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel49.setText("MOD BALANCE");
        jPanel8.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 260, 170, 30));

        jTextField13.setEditable(false);
        jTextField13.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField13.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel8.add(jTextField13, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 300, 210, 30));

        jLabel50.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel50.setText("NOMINATION REGISTERED");
        jPanel8.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 230, 30));

        jButton14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton14.setText("SEARCH");
        jButton14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton14ActionPerformed(evt);
            }
        });
        jPanel8.add(jButton14, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 20, 130, 30));

        jTabbedPane1.addTab("VIEW BALANCE", jPanel8);

        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("ENTER NEW PIN:");
        jPanel9.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 160, 30));

        jTextField14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField14.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jTextField14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 100, 230, 30));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel3.setText("ENTER OLD PIN:");
        jPanel9.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 50, 160, 30));

        jTextField15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jTextField15.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel9.add(jTextField15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 230, 30));

        jButton15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton15.setText("CLEAR");
        jButton15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton15ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton15, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 140, 110, 30));

        jButton16.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jButton16.setText("CHANGE");
        jButton16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton16ActionPerformed(evt);
            }
        });
        jPanel9.add(jButton16, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 140, 110, 30));

        jTabbedPane1.addTab("CHANGE PIN", jPanel9);

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 873, Short.MAX_VALUE)
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 404, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("ABOUT", jPanel10);

        jPanel1.add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 90, 880, 440));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("BANKS MANAGEMENT SYSTEM");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 280, 40));

        jLabel14.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel14.setText("USER");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 100, 30));

        txtuser.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtuser.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtuser, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 10, 170, 30));

        jLabel15.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel15.setText("DATE");
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 100, 30));

        txtdate.setEditable(false);
        txtdate.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        txtdate.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel1.add(txtdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 50, 170, 30));

        jButton2.setText("SHOW");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 10, -1, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 899, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 542, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        F1.setEditable(true);
        F2.setEditable(true);
        F3.setEditable(true);
        F4.setEditable(true);
        F5.setEditable(true);
        F6.setEditable(true);
        F7.setEditable(true);
        F8.setEditable(true);
        F9.setEditable(true);
        F10.setEditable(true);
        Alert a = new Alert();
        a.setVisible(true);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        
        try {
            String query = "SELECT * FROM accounts WHERE name='"+txtuser.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                F1.setText(rs.getString("name")); 
                F2.setText(rs.getString("date_of_birth")); 
                F3.setText(rs.getString("nationality"));
                F4.setText(rs.getString("gender")); 
                F5.setText(rs.getString("address")); 
                F6.setText(rs.getString("account_no"));                 
                F7.setText(rs.getString("account_type"));
                F8.setText(rs.getString("caste")); 
                F9.setText(rs.getString("mobile")); 
                F10.setText(rs.getString("sec_q")); 
            
                rs.close();
                pst.close();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter Correct Name");
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       
    
        String s3 = F3.getText();
        String s4 = F4.getText();
        String s5 = F5.getText();
        String s8 = F8.getText();
        String s9 = F9.getText();
        String s10 = F10.getText();
        
        try {
            String update = "UPDATE `accounts` SET `Name`='"+F1.getText()+"',"
                    + "`Nationality`='"+s3+"',"                    
                    + "`Gender`='"+s4+"',"              
                    + "`Address`='"+s5+"',"
                    + "`Caste`='"+s8+"',"
                    + "`Mobile`='"+s9+"',"
                    + "`Sec_Q`='"+s10+"' WHERE `Account_no`='"+F6.getText()+"'";           
            pst=conn.prepareStatement(update);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Profile Updated");
            showCustomer();
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        try {
            String query = "SELECT * FROM balance WHERE name='"+USER.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                NAME.setText(rs.getString("name"));
                ACCOUNTNO.setText(rs.getString("account"));
                BALANCE.setText(rs.getString("balances"));
                rs.close();
                pst.close();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter Correct Name");
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        try {           
            String val1 = BALANCE.getText();
            String val2 = DEPOSITAMOUNT.getText();
            int sum = Integer.parseInt(val1)+Integer.parseInt(val2);
            String sum1 = String.valueOf(sum);
            TOTAL.setText(sum1);
            
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        try {
            String query = "UPDATE balance SET balances='"+TOTAL.getText()+"' WHERE name='"+NAME.getText()+"'";
            pst=conn.prepareStatement(query);
            pst.execute();
            JOptionPane.showMessageDialog(rootPane, "Deposit Success");
            showBalance();
            
            USER.setText("");
            NAME.setText("");
            ACCOUNTNO.setText("");
            BALANCE.setText("");
            DEPOSITAMOUNT.setText("");
            TOTAL.setText("");
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        
           try {
            String query = "SELECT * FROM balance WHERE name='"+txtUser.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                txtName.setText(rs.getString("name"));
                txtAccountNo.setText(rs.getString("account"));
                txtAvailableBalance.setText(rs.getString("balances"));
                rs.close();
                pst.close();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter Correct Name");
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        try {           
            String value1 = txtAvailableBalance.getText();
            String value2 = txtTranferAmount.getText();
            int minus = Integer.parseInt(value1)-Integer.parseInt(value2);
            String min = String.valueOf(minus);
            txtTotaltransfer.setText(min);
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


public void Account(){
    try {
        String query = "SELECT * FROM balance";
        pst=conn.prepareStatement(query);
        rs=pst.executeQuery();
        while (rs.next()) {            
            String acc = rs.getString("account");
            jComboBox1.addItem(acc);
        }
    } catch (Exception e) {
    }
}

    private void jComboBox1PopupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jComboBox1PopupMenuWillBecomeInvisible
      
        try {           
            String sql = "SELECT * FROM balance WHERE account='"+jComboBox1.getSelectedItem().toString()+"'";
            pst=conn.prepareStatement(sql);
            rs=pst.executeQuery();
            if(rs.next()){
                jTextfield25.setText(rs.getString("balances"));
            }
            
        } catch (SQLException e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jComboBox1PopupMenuWillBecomeInvisible

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
      
            try {           
            String value1 = txtTotaltransfer.getText();
            String value2 = jTextfield25.getText();
            int minus = Integer.parseInt(value1)+Integer.parseInt(value2);
            String min = String.valueOf(minus);
            jTextfield24.setText(min);
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
        
    }//GEN-LAST:event_jButton10ActionPerformed
public void TransferC(){
    try {
        String values1 = (String)jComboBox1.getSelectedItem();
        String values2 = txtTotaltransfer.getText();
        String query = "UPDATE balance SET balances='"+values2+"' WHERE account='"+values1+"'";
        pst=conn.prepareStatement(query);
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Successfully Transfered");
        showBalance();
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e);
    }
}

public void TransferD(){
    try {
        String adds1 = txtUser.getText();
        String adds2 = jTextfield24.getText();
        String query = "UPDATE balance SET balances='"+adds2+"' WHERE name='"+adds1+"'";
        pst=conn.prepareStatement(query);
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Successfully Transfered");
        showBalance();
        
    } catch (Exception e) {
         JOptionPane.showMessageDialog(rootPane, e);
    }
}
    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
       TransferC();
       TransferD();
       showBalance();
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
             try {
            String query = "SELECT * FROM balance WHERE name='"+jTextField1.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                txtName1.setText(rs.getString("name"));
                jTextField2.setText(rs.getString("account"));
                jTextField3.setText(rs.getString("balances"));
                rs.close();
                pst.close();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter Correct Name");
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void jButton13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton13ActionPerformed
           try {           
            String value1 = jTextField3.getText();
            String value2 = jTextField4.getText();
            int minus = Integer.parseInt(value1)-Integer.parseInt(value2);
            String min = String.valueOf(minus);
            jTextField5.setText(min);
            
            
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(rootPane, e);
        }
    }//GEN-LAST:event_jButton13ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
        try {
        String ad1 = jTextField1.getText();
        String ad2 = jTextField5.getText();
        String query = "UPDATE balance SET balances='"+ad2+"' WHERE name='"+ad1+"'";
        pst=conn.prepareStatement(query);
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Successfully Withdraw");
        showBalance();
        
    } catch (HeadlessException | SQLException e) {
         JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton11ActionPerformed

    private void jButton14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton14ActionPerformed
              try {
            String query = "SELECT * FROM balance WHERE name='"+jTextField6.getText()+"'";
            pst=conn.prepareStatement(query);
            rs=pst.executeQuery();
            if(rs.next()){
                jTextField7.setText(rs.getString("name"));
                jTextField8.setText(rs.getString("account"));
                jTextField9.setText(rs.getString("micr_NO"));                
                jTextField11.setText(rs.getString("balances"));
                jTextField10.setText("4 %");
                jTextField12.setText("Rs 0.00");
                jTextField13.setText("No");
                rs.close();
                pst.close();
            }else{
                JOptionPane.showMessageDialog(rootPane, "Enter Correct Name");
            }
            
        } catch (Exception e) {
             JOptionPane.showMessageDialog(rootPane, e);
        }finally{
            try {
                rs.close();
                pst.close();
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_jButton14ActionPerformed

    private void jButton15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton15ActionPerformed
        jTextField14.setText("");
        jTextField14.setToolTipText("Enter New Pin");
        jTextField15.setText("");
        jTextField15.setToolTipText("Enter Old Pin");
        
    }//GEN-LAST:event_jButton15ActionPerformed

    private void jButton16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton16ActionPerformed
        try {
        String ad1 = F1.getText();
        String ad2 = jTextField14.getText();
        String query = "UPDATE accounts SET pin='"+ad2+"' WHERE name='"+ad1+"'";
        pst=conn.prepareStatement(query);
        pst.execute();
        JOptionPane.showMessageDialog(rootPane, "Pin Successfully Change");
        showBalance();
        
    } catch (HeadlessException | SQLException e) {
         JOptionPane.showMessageDialog(rootPane, e);
    }
    }//GEN-LAST:event_jButton16ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                /*if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }*/
                  UIManager.setLookAndFeel("com.jtattoo.plaf.smart.SmartLookAndFeel");
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mypage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mypage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField ACCOUNTNO;
    private javax.swing.JTextField BALANCE;
    private javax.swing.JTextField DEPOSITAMOUNT;
    private javax.swing.JTextField F1;
    private javax.swing.JTextField F10;
    private javax.swing.JTextField F2;
    private javax.swing.JTextField F3;
    private javax.swing.JTextField F4;
    private javax.swing.JTextField F5;
    private javax.swing.JTextField F6;
    private javax.swing.JTextField F7;
    private javax.swing.JTextField F8;
    private javax.swing.JTextField F9;
    private javax.swing.JTextField NAME;
    private javax.swing.JTextField TOTAL;
    private javax.swing.JTextField USER;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton13;
    private javax.swing.JButton jButton14;
    private javax.swing.JButton jButton15;
    private javax.swing.JButton jButton16;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField14;
    private javax.swing.JTextField jTextField15;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    private javax.swing.JTextField jTextfield24;
    private javax.swing.JTextField jTextfield25;
    private javax.swing.JTextField txtAccountNo;
    private javax.swing.JTextField txtAvailableBalance;
    private javax.swing.JTextField txtName;
    private javax.swing.JTextField txtName1;
    private javax.swing.JTextField txtTotaltransfer;
    private javax.swing.JTextField txtTranferAmount;
    private javax.swing.JTextField txtUser;
    private javax.swing.JTextField txtdate;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
